import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { Profile, Chat, useBeoble } from '@beoble/react';
import ConnectButton from '../components/Web3Button';
import { useWeb3Context } from '../components/Web3Button/web3Context';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { connect, address } = useWeb3Context();
  const handleConnect = () => {
    connect();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {address ? (
        <>
          <div className={styles.appbar}>
            <Profile detailElement="modal" />
            <Chat />
          </div>
          <main className={styles.main}>
            <h1 className={styles.title}>
              Welcome to <a href="https://beoble.io">beoble!</a>
            </h1>

            <p className={styles.description}>
              your address is <code className={styles.code}>{address}</code>
            </p>
          </main>
        </>
      ) : (
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://beoble.io">beoble!</a>
          </h1>

          <p className={styles.description}>
            Get started by adding{' '}
            <code className={styles.code}>Widget/Profile.tsx</code>
          </p>
          {/*<Profile detailElement={'modal'} />*/}
          <ConnectButton onClick={handleConnect} />
        </main>
      )}

      <footer className={styles.footer}>
        <a href="https://beoble.io" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src="/beoble_horizontal_black.png"
              alt="Vercel Logo"
              width={72}
              height={28.61}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
